development:
  # Sqlite3 Settings
  #adapter: sqlite3
  #database: db/development.sqlite3
  #timeout: 5000
  
  # Mysql Settings
   adapter: mysql
   encoding: utf8
   charset: utf8
   database: seed_development
   username: root
   password:
   host: localhost

test:
  # Sqlite3 Settings
  #adapter: sqlite3
  #database: db/test.sqlite3
  #timeout: 5000
  
  # Mysql Settings
   adapter: mysql
   encoding: utf8
   charset: utf8
   database: seed_test
   username: root
   password:
   host: localhost
